//File Automatically generated by SystemC Netlister Time
#include "bd_5dca_sci.h"
bd_5dca_sci::bd_5dca_sci(const sc_module_name& module_name) : xsc::utils::xsc_sim_conn_base(module_name) 
{
	//Exported sockets Instantiation
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("bd_5dca_sci","S01_AXI_tlm_MODE",0,"bd_5dca_interconnect1_0_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("bd_5dca_sci","S01_AXI_tlm_MODE",0,"bd_5dca_interconnect1_0_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("bd_5dca_sci","S02_AXI_tlm_MODE",0,"bd_5dca_interconnect2_1_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("bd_5dca_sci","S02_AXI_tlm_MODE",0,"bd_5dca_interconnect2_1_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("bd_5dca_sci","S00_AXI_tlm_MODE",0,"bd_5dca_interconnect0_2_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("bd_5dca_sci","S00_AXI_tlm_MODE",0,"bd_5dca_interconnect0_2_0","S00_AXI_tlm_MODE");
	
	//Add TLM Parameters
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_interconnect1_0_0","M00_AXI_tlm_MODE","bd_5dca_slice1_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_interconnect1_0_0","M00_AXI_tlm_MODE","bd_5dca_slice1_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_interconnect2_1_0","M00_AXI_tlm_MODE","bd_5dca_slice2_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_interconnect2_1_0","M00_AXI_tlm_MODE","bd_5dca_slice2_1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_interconnect0_2_0","M00_AXI_tlm_MODE","bd_5dca_slice0_2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_interconnect0_2_0","M00_AXI_tlm_MODE","bd_5dca_slice0_2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_slice1_0_0","M_AXI_TLM_MODE","bd_5dca_vip_S01_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_slice1_0_0","M_AXI_TLM_MODE","bd_5dca_vip_S01_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_vip_S01_0","M_AXI_TLM_MODE","bd_5dca_hbm_inst_0","SAXI_00_8HI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_vip_S01_0","M_AXI_TLM_MODE","bd_5dca_hbm_inst_0","SAXI_00_8HI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_slice2_1_0","M_AXI_TLM_MODE","bd_5dca_vip_S02_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_slice2_1_0","M_AXI_TLM_MODE","bd_5dca_vip_S02_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_vip_S02_0","M_AXI_TLM_MODE","bd_5dca_hbm_inst_0","SAXI_01_8HI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_vip_S02_0","M_AXI_TLM_MODE","bd_5dca_hbm_inst_0","SAXI_01_8HI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_slice0_2_0","M_AXI_TLM_MODE","bd_5dca_vip_S00_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_slice0_2_0","M_AXI_TLM_MODE","bd_5dca_vip_S00_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_vip_S00_0","M_AXI_TLM_MODE","bd_5dca_hbm_inst_0","SAXI_02_8HI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("bd_5dca_vip_S00_0","M_AXI_TLM_MODE","bd_5dca_hbm_inst_0","SAXI_02_8HI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("bd_5dca_sci","S_AXI_CTRL_TLM_MODE",-1);
	
	xsc::utils::xsc_sim_manager::addInstance("bd_5dca_sci", this);
	#if defined MTI_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()) {
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	scv_startup(); /* Initialize SCV: */
	scv_tr_wlf_init(); /* Tie databases to WLF: */
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
	#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()){
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	cve_tr_sdi_init();
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
}
bd_5dca_sci::~bd_5dca_sci()
{
}
void bd_5dca_sci::initConnModule() {

	bd_5dca_interconnect1_0_0_sc*  inst0=dynamic_cast<bd_5dca_interconnect1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect1_0_0"));
	registerTlmSocket("S01_AXI_tlm_aximm_read_socket",inst0->S00_AXI_tlm_aximm_read_socket);
	bd_5dca_interconnect1_0_0_sc*  inst1=dynamic_cast<bd_5dca_interconnect1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect1_0_0"));
	registerTlmSocket("S01_AXI_tlm_aximm_write_socket",inst1->S00_AXI_tlm_aximm_write_socket);
	bd_5dca_interconnect2_1_0_sc*  inst2=dynamic_cast<bd_5dca_interconnect2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect2_1_0"));
	registerTlmSocket("S02_AXI_tlm_aximm_read_socket",inst2->S00_AXI_tlm_aximm_read_socket);
	bd_5dca_interconnect2_1_0_sc*  inst3=dynamic_cast<bd_5dca_interconnect2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect2_1_0"));
	registerTlmSocket("S02_AXI_tlm_aximm_write_socket",inst3->S00_AXI_tlm_aximm_write_socket);
	bd_5dca_interconnect0_2_0_sc*  inst4=dynamic_cast<bd_5dca_interconnect0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect0_2_0"));
	registerTlmSocket("S00_AXI_tlm_aximm_read_socket",inst4->S00_AXI_tlm_aximm_read_socket);
	bd_5dca_interconnect0_2_0_sc*  inst5=dynamic_cast<bd_5dca_interconnect0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect0_2_0"));
	registerTlmSocket("S00_AXI_tlm_aximm_write_socket",inst5->S00_AXI_tlm_aximm_write_socket);
}

void bd_5dca_sci::before_end_of_elaboration() {
	
	bd_5dca_interconnect1_0_0_sc*  inst_0=dynamic_cast<bd_5dca_interconnect1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect1_0_0"));
	bd_5dca_slice1_0_0_sc*  inst_1=dynamic_cast<bd_5dca_slice1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice1_0_0"));
	xtlm_aximm_transaction_logger* log_inst_0 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_0");
	log_inst_0->setProxyRef(inst_0, inst_1, "bd_5dca_interconnect1_0_0_M00_AXI_tlm", "bd_5dca_slice1_0_0_S_AXI_TLM", log_inst_0->m_transactionLogger);
	
	if(inst_0==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_interconnect1_0_0_sc"<<std::endl;
	}
	if(inst_1==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice1_0_0_sc"<<std::endl;
	}
	
	if (inst_0!=NULL && inst_1!=NULL) {
		inst_0->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_0->tar_rd_skt));
		log_inst_0->init_rd_skt->bind(*(inst_1->S_TARGET_rd_socket));
	}
	
	bd_5dca_interconnect1_0_0_sc*  inst_4=dynamic_cast<bd_5dca_interconnect1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect1_0_0"));
	bd_5dca_slice1_0_0_sc*  inst_5=dynamic_cast<bd_5dca_slice1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice1_0_0"));
	
	if(inst_4==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_interconnect1_0_0_sc"<<std::endl;
	}
	if(inst_5==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice1_0_0_sc"<<std::endl;
	}
	
	if (inst_4!=NULL && inst_5!=NULL) {
		inst_4->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_0->tar_wr_skt));
		log_inst_0->init_wr_skt->bind(*(inst_5->S_TARGET_wr_socket));
	}
	
	bd_5dca_interconnect2_1_0_sc*  inst_8=dynamic_cast<bd_5dca_interconnect2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect2_1_0"));
	bd_5dca_slice2_1_0_sc*  inst_9=dynamic_cast<bd_5dca_slice2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice2_1_0"));
	xtlm_aximm_transaction_logger* log_inst_1 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_1");
	log_inst_1->setProxyRef(inst_8, inst_9, "bd_5dca_interconnect2_1_0_M00_AXI_tlm", "bd_5dca_slice2_1_0_S_AXI_TLM", log_inst_1->m_transactionLogger);
	
	if(inst_8==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_interconnect2_1_0_sc"<<std::endl;
	}
	if(inst_9==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice2_1_0_sc"<<std::endl;
	}
	
	if (inst_8!=NULL && inst_9!=NULL) {
		inst_8->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_1->tar_rd_skt));
		log_inst_1->init_rd_skt->bind(*(inst_9->S_TARGET_rd_socket));
	}
	
	bd_5dca_interconnect2_1_0_sc*  inst_12=dynamic_cast<bd_5dca_interconnect2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect2_1_0"));
	bd_5dca_slice2_1_0_sc*  inst_13=dynamic_cast<bd_5dca_slice2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice2_1_0"));
	
	if(inst_12==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_interconnect2_1_0_sc"<<std::endl;
	}
	if(inst_13==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice2_1_0_sc"<<std::endl;
	}
	
	if (inst_12!=NULL && inst_13!=NULL) {
		inst_12->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_1->tar_wr_skt));
		log_inst_1->init_wr_skt->bind(*(inst_13->S_TARGET_wr_socket));
	}
	
	bd_5dca_interconnect0_2_0_sc*  inst_16=dynamic_cast<bd_5dca_interconnect0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect0_2_0"));
	bd_5dca_slice0_2_0_sc*  inst_17=dynamic_cast<bd_5dca_slice0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice0_2_0"));
	xtlm_aximm_transaction_logger* log_inst_2 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_2");
	log_inst_2->setProxyRef(inst_16, inst_17, "bd_5dca_interconnect0_2_0_M00_AXI_tlm", "bd_5dca_slice0_2_0_S_AXI_TLM", log_inst_2->m_transactionLogger);
	
	if(inst_16==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_interconnect0_2_0_sc"<<std::endl;
	}
	if(inst_17==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice0_2_0_sc"<<std::endl;
	}
	
	if (inst_16!=NULL && inst_17!=NULL) {
		inst_16->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_2->tar_rd_skt));
		log_inst_2->init_rd_skt->bind(*(inst_17->S_TARGET_rd_socket));
	}
	
	bd_5dca_interconnect0_2_0_sc*  inst_20=dynamic_cast<bd_5dca_interconnect0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_interconnect0_2_0"));
	bd_5dca_slice0_2_0_sc*  inst_21=dynamic_cast<bd_5dca_slice0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice0_2_0"));
	
	if(inst_20==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_interconnect0_2_0_sc"<<std::endl;
	}
	if(inst_21==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice0_2_0_sc"<<std::endl;
	}
	
	if (inst_20!=NULL && inst_21!=NULL) {
		inst_20->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_2->tar_wr_skt));
		log_inst_2->init_wr_skt->bind(*(inst_21->S_TARGET_wr_socket));
	}
	
	bd_5dca_slice1_0_0_sc*  inst_24=dynamic_cast<bd_5dca_slice1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice1_0_0"));
	bd_5dca_vip_S01_0_sc*  inst_25=dynamic_cast<bd_5dca_vip_S01_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S01_0"));
	xtlm_aximm_transaction_logger* log_inst_3 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_3");
	log_inst_3->setProxyRef(inst_24, inst_25, "bd_5dca_slice1_0_0_M_AXI_TLM", "bd_5dca_vip_S01_0_S_AXI_TLM", log_inst_3->m_transactionLogger);
	
	if(inst_24==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice1_0_0_sc"<<std::endl;
	}
	if(inst_25==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S01_0_sc"<<std::endl;
	}
	
	if (inst_24!=NULL && inst_25!=NULL) {
		inst_24->M_INITIATOR_rd_socket->bind(*(log_inst_3->tar_rd_skt));
		log_inst_3->init_rd_skt->bind(*(inst_25->S_TARGET_rd_socket));
	}
	
	bd_5dca_slice1_0_0_sc*  inst_28=dynamic_cast<bd_5dca_slice1_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice1_0_0"));
	bd_5dca_vip_S01_0_sc*  inst_29=dynamic_cast<bd_5dca_vip_S01_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S01_0"));
	
	if(inst_28==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice1_0_0_sc"<<std::endl;
	}
	if(inst_29==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S01_0_sc"<<std::endl;
	}
	
	if (inst_28!=NULL && inst_29!=NULL) {
		inst_28->M_INITIATOR_wr_socket->bind(*(log_inst_3->tar_wr_skt));
		log_inst_3->init_wr_skt->bind(*(inst_29->S_TARGET_wr_socket));
	}
	
	bd_5dca_vip_S01_0_sc*  inst_32=dynamic_cast<bd_5dca_vip_S01_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S01_0"));
	bd_5dca_hbm_inst_0_sc*  inst_33=dynamic_cast<bd_5dca_hbm_inst_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_hbm_inst_0"));
	xtlm_aximm_transaction_logger* log_inst_4 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_4");
	log_inst_4->setProxyRef(inst_32, inst_33, "bd_5dca_vip_S01_0_M_AXI_TLM", "bd_5dca_hbm_inst_0_SAXI_00_8HI_TLM", log_inst_4->m_transactionLogger);
	
	if(inst_32==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S01_0_sc"<<std::endl;
	}
	if(inst_33==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_hbm_inst_0_sc"<<std::endl;
	}
	
	if (inst_32!=NULL && inst_33!=NULL) {
		inst_32->M_INITIATOR_rd_socket->bind(*(log_inst_4->tar_rd_skt));
		log_inst_4->init_rd_skt->bind(*(inst_33->SAXI_00_8HI_rd_socket));
	}
	
	bd_5dca_vip_S01_0_sc*  inst_36=dynamic_cast<bd_5dca_vip_S01_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S01_0"));
	bd_5dca_hbm_inst_0_sc*  inst_37=dynamic_cast<bd_5dca_hbm_inst_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_hbm_inst_0"));
	
	if(inst_36==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S01_0_sc"<<std::endl;
	}
	if(inst_37==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_hbm_inst_0_sc"<<std::endl;
	}
	
	if (inst_36!=NULL && inst_37!=NULL) {
		inst_36->M_INITIATOR_wr_socket->bind(*(log_inst_4->tar_wr_skt));
		log_inst_4->init_wr_skt->bind(*(inst_37->SAXI_00_8HI_wr_socket));
	}
	
	bd_5dca_slice2_1_0_sc*  inst_40=dynamic_cast<bd_5dca_slice2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice2_1_0"));
	bd_5dca_vip_S02_0_sc*  inst_41=dynamic_cast<bd_5dca_vip_S02_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S02_0"));
	xtlm_aximm_transaction_logger* log_inst_5 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_5");
	log_inst_5->setProxyRef(inst_40, inst_41, "bd_5dca_slice2_1_0_M_AXI_TLM", "bd_5dca_vip_S02_0_S_AXI_TLM", log_inst_5->m_transactionLogger);
	
	if(inst_40==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice2_1_0_sc"<<std::endl;
	}
	if(inst_41==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S02_0_sc"<<std::endl;
	}
	
	if (inst_40!=NULL && inst_41!=NULL) {
		inst_40->M_INITIATOR_rd_socket->bind(*(log_inst_5->tar_rd_skt));
		log_inst_5->init_rd_skt->bind(*(inst_41->S_TARGET_rd_socket));
	}
	
	bd_5dca_slice2_1_0_sc*  inst_44=dynamic_cast<bd_5dca_slice2_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice2_1_0"));
	bd_5dca_vip_S02_0_sc*  inst_45=dynamic_cast<bd_5dca_vip_S02_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S02_0"));
	
	if(inst_44==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice2_1_0_sc"<<std::endl;
	}
	if(inst_45==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S02_0_sc"<<std::endl;
	}
	
	if (inst_44!=NULL && inst_45!=NULL) {
		inst_44->M_INITIATOR_wr_socket->bind(*(log_inst_5->tar_wr_skt));
		log_inst_5->init_wr_skt->bind(*(inst_45->S_TARGET_wr_socket));
	}
	
	bd_5dca_vip_S02_0_sc*  inst_48=dynamic_cast<bd_5dca_vip_S02_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S02_0"));
	bd_5dca_hbm_inst_0_sc*  inst_49=dynamic_cast<bd_5dca_hbm_inst_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_hbm_inst_0"));
	xtlm_aximm_transaction_logger* log_inst_6 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_6");
	log_inst_6->setProxyRef(inst_48, inst_49, "bd_5dca_vip_S02_0_M_AXI_TLM", "bd_5dca_hbm_inst_0_SAXI_01_8HI_TLM", log_inst_6->m_transactionLogger);
	
	if(inst_48==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S02_0_sc"<<std::endl;
	}
	if(inst_49==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_hbm_inst_0_sc"<<std::endl;
	}
	
	if (inst_48!=NULL && inst_49!=NULL) {
		inst_48->M_INITIATOR_rd_socket->bind(*(log_inst_6->tar_rd_skt));
		log_inst_6->init_rd_skt->bind(*(inst_49->SAXI_01_8HI_rd_socket));
	}
	
	bd_5dca_vip_S02_0_sc*  inst_52=dynamic_cast<bd_5dca_vip_S02_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S02_0"));
	bd_5dca_hbm_inst_0_sc*  inst_53=dynamic_cast<bd_5dca_hbm_inst_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_hbm_inst_0"));
	
	if(inst_52==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S02_0_sc"<<std::endl;
	}
	if(inst_53==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_hbm_inst_0_sc"<<std::endl;
	}
	
	if (inst_52!=NULL && inst_53!=NULL) {
		inst_52->M_INITIATOR_wr_socket->bind(*(log_inst_6->tar_wr_skt));
		log_inst_6->init_wr_skt->bind(*(inst_53->SAXI_01_8HI_wr_socket));
	}
	
	bd_5dca_slice0_2_0_sc*  inst_56=dynamic_cast<bd_5dca_slice0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice0_2_0"));
	bd_5dca_vip_S00_0_sc*  inst_57=dynamic_cast<bd_5dca_vip_S00_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S00_0"));
	xtlm_aximm_transaction_logger* log_inst_7 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_7");
	log_inst_7->setProxyRef(inst_56, inst_57, "bd_5dca_slice0_2_0_M_AXI_TLM", "bd_5dca_vip_S00_0_S_AXI_TLM", log_inst_7->m_transactionLogger);
	
	if(inst_56==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice0_2_0_sc"<<std::endl;
	}
	if(inst_57==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S00_0_sc"<<std::endl;
	}
	
	if (inst_56!=NULL && inst_57!=NULL) {
		inst_56->M_INITIATOR_rd_socket->bind(*(log_inst_7->tar_rd_skt));
		log_inst_7->init_rd_skt->bind(*(inst_57->S_TARGET_rd_socket));
	}
	
	bd_5dca_slice0_2_0_sc*  inst_60=dynamic_cast<bd_5dca_slice0_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_slice0_2_0"));
	bd_5dca_vip_S00_0_sc*  inst_61=dynamic_cast<bd_5dca_vip_S00_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S00_0"));
	
	if(inst_60==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_slice0_2_0_sc"<<std::endl;
	}
	if(inst_61==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S00_0_sc"<<std::endl;
	}
	
	if (inst_60!=NULL && inst_61!=NULL) {
		inst_60->M_INITIATOR_wr_socket->bind(*(log_inst_7->tar_wr_skt));
		log_inst_7->init_wr_skt->bind(*(inst_61->S_TARGET_wr_socket));
	}
	
	bd_5dca_vip_S00_0_sc*  inst_64=dynamic_cast<bd_5dca_vip_S00_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S00_0"));
	bd_5dca_hbm_inst_0_sc*  inst_65=dynamic_cast<bd_5dca_hbm_inst_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_hbm_inst_0"));
	xtlm_aximm_transaction_logger* log_inst_8 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_8");
	log_inst_8->setProxyRef(inst_64, inst_65, "bd_5dca_vip_S00_0_M_AXI_TLM", "bd_5dca_hbm_inst_0_SAXI_02_8HI_TLM", log_inst_8->m_transactionLogger);
	
	if(inst_64==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S00_0_sc"<<std::endl;
	}
	if(inst_65==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_hbm_inst_0_sc"<<std::endl;
	}
	
	if (inst_64!=NULL && inst_65!=NULL) {
		inst_64->M_INITIATOR_rd_socket->bind(*(log_inst_8->tar_rd_skt));
		log_inst_8->init_rd_skt->bind(*(inst_65->SAXI_02_8HI_rd_socket));
	}
	
	bd_5dca_vip_S00_0_sc*  inst_68=dynamic_cast<bd_5dca_vip_S00_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_vip_S00_0"));
	bd_5dca_hbm_inst_0_sc*  inst_69=dynamic_cast<bd_5dca_hbm_inst_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_hbm_inst_0"));
	
	if(inst_68==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_vip_S00_0_sc"<<std::endl;
	}
	if(inst_69==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind bd_5dca_hbm_inst_0_sc"<<std::endl;
	}
	
	if (inst_68!=NULL && inst_69!=NULL) {
		inst_68->M_INITIATOR_wr_socket->bind(*(log_inst_8->tar_wr_skt));
		log_inst_8->init_wr_skt->bind(*(inst_69->SAXI_02_8HI_wr_socket));
	}
	
}
#ifdef MTI_SYSTEMC
SC_MODULE_EXPORT(bd_5dca_sci);
#endif

#ifdef XM_SYSTEMC
XMSC_MODULE_EXPORT(bd_5dca_sci);
#endif

#ifdef RIVIERA
SC_MODULE_EXPORT(bd_5dca_sci);
#endif

