//File Automatically generated by SystemC Netlister Time
#include "pfm_dynamic_sci.h"
pfm_dynamic_sci::pfm_dynamic_sci(const sc_module_name& module_name) : xsc::utils::xsc_sim_conn_base(module_name) 
{
	//Exported sockets Instantiation
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","BLP_M_AXI_DATA_C2H_00_tlm_MODE",0,"bd_d216_sci","M00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","BLP_M_AXI_DATA_C2H_00_tlm_MODE",0,"bd_d216_sci","M00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","BLP_S_AXI_DATA_H2C_00_tlm_MODE",0,"pfm_dynamic_smartconn_data_0_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","BLP_S_AXI_DATA_H2C_00_tlm_MODE",0,"pfm_dynamic_smartconn_data_0_0","S00_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","BLP_S_AXI_CTRL_USER_00_tlm_MODE",0,"pfm_dynamic_xbar_3","S00_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","BLP_S_AXI_CTRL_USER_00_tlm_MODE",0,"pfm_dynamic_xbar_3","S00_AXI_TLM_MODE");
	
	//Add TLM Parameters
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_0","M_AXI_TLM_MODE","pfm_dynamic_m02_regslice_4","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_0","M_AXI_TLM_MODE","pfm_dynamic_m02_regslice_4","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_3","M01_AXI_TLM_MODE","pfm_dynamic_m01_regslice_4","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_3","M01_AXI_TLM_MODE","pfm_dynamic_m01_regslice_4","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_3","M02_AXI_TLM_MODE","pfm_dynamic_auto_cc_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_3","M02_AXI_TLM_MODE","pfm_dynamic_auto_cc_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_1","M_AXI_TLM_MODE","pfm_dynamic_m00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_1","M_AXI_TLM_MODE","pfm_dynamic_m00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_2","M_AXI_TLM_MODE","pfm_dynamic_m01_regslice_5","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_2","M_AXI_TLM_MODE","pfm_dynamic_m01_regslice_5","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_3","M_AXI_TLM_MODE","pfm_dynamic_m02_regslice_5","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_3","M_AXI_TLM_MODE","pfm_dynamic_m02_regslice_5","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_4","M_AXI_TLM_MODE","pfm_dynamic_m03_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_4","M_AXI_TLM_MODE","pfm_dynamic_m03_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_5","M_AXI_TLM_MODE","pfm_dynamic_m04_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_auto_cc_5","M_AXI_TLM_MODE","pfm_dynamic_m04_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_s00_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_xbar_4","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_s00_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_xbar_4","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M00_AXI_TLM_MODE","pfm_dynamic_auto_cc_1","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M00_AXI_TLM_MODE","pfm_dynamic_auto_cc_1","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M01_AXI_TLM_MODE","pfm_dynamic_auto_cc_2","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M01_AXI_TLM_MODE","pfm_dynamic_auto_cc_2","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M02_AXI_TLM_MODE","pfm_dynamic_auto_cc_3","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M02_AXI_TLM_MODE","pfm_dynamic_auto_cc_3","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M03_AXI_TLM_MODE","pfm_dynamic_auto_cc_4","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M03_AXI_TLM_MODE","pfm_dynamic_auto_cc_4","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M04_AXI_TLM_MODE","pfm_dynamic_auto_cc_5","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xbar_4","M04_AXI_TLM_MODE","pfm_dynamic_auto_cc_5","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m00_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIFIFO_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m00_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIFIFO_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m01_regslice_5","M_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIHUB_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m01_regslice_5","M_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIHUB_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m02_regslice_5","M_AXI_TLM_MODE","pfm_dynamic_dpa_mon0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m02_regslice_5","M_AXI_TLM_MODE","pfm_dynamic_dpa_mon0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m03_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_mon1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m03_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_mon1_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m04_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_mon2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m04_regslice_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_mon2_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon0_0","TRACE_OUT_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_0_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon1_0","TRACE_OUT_0_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_1_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon1_0","TRACE_OUT_1_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_2_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon2_0","TRACE_OUT_0_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_3_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon2_0","TRACE_OUT_1_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_4_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_profile_vip_0_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_profile_vip_0_0","M_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_smartconn_data_0_0","M00_AXI_tlm_MODE","bd_d216_sci","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_smartconn_data_0_0","M00_AXI_tlm_MODE","bd_d216_sci","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_smartconn_data_0_0","M01_AXI_tlm_MODE","bd_5dca_sci","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_smartconn_data_0_0","M01_AXI_tlm_MODE","bd_5dca_sci","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_smartconn_data_0_0","M02_AXI_tlm_MODE","pfm_dynamic_profile_vip_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_smartconn_data_0_0","M02_AXI_tlm_MODE","pfm_dynamic_profile_vip_0_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m01_regslice_4","M_AXI_TLM_MODE","pfm_dynamic_s00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_m01_regslice_4","M_AXI_TLM_MODE","pfm_dynamic_s00_regslice_0","S_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("pfm_dynamic_sci","S_AXI_CTRL_1_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("pfm_dynamic_sci","BLP_S_AXI_CTRL_USER_02_TLM_MODE",-1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("pfm_dynamic_sci","BLP_S_AXI_CTRL_USER_01_TLM_MODE",-1);
	
	xsc::utils::xsc_sim_manager::addInstance("pfm_dynamic_sci", this);
	#if defined MTI_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()) {
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	scv_startup(); /* Initialize SCV: */
	scv_tr_wlf_init(); /* Tie databases to WLF: */
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
	#if defined XM_SYSTEMC && defined XSC_ENABLE_TLM_WAVEFORM
	if(!xsc::utils::xsc_sim_manager::isMTlmWaveDatabaseInit()){
	xsc::utils::xsc_sim_manager::setMTlmWaveDatabaseInit(true);
	cve_tr_sdi_init();
	scv_tr_db *txdb = new scv_tr_db("tlmWaveDB");
	if (txdb != NULL)
	  scv_tr_db::set_default_db(txdb);
	}
	#endif
}
pfm_dynamic_sci::~pfm_dynamic_sci()
{
}
void pfm_dynamic_sci::initConnModule() {

	xsc_sim_conn_base*  inst0=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_d216_sci"));
	if (inst0!=nullptr) {
	registerTlmSocket("BLP_M_AXI_DATA_C2H_00_tlm_aximm_read_socket",inst0->getTlmSocketByName("M00_AXI_tlm_aximm_read_socket"));
	}
	xsc_sim_conn_base*  inst1=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_d216_sci"));
	if (inst1!=nullptr) {
	registerTlmSocket("BLP_M_AXI_DATA_C2H_00_tlm_aximm_write_socket",inst1->getTlmSocketByName("M00_AXI_tlm_aximm_write_socket"));
	}
	pfm_dynamic_smartconn_data_0_0_sc*  inst2=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	registerTlmSocket("BLP_S_AXI_DATA_H2C_00_tlm_aximm_read_socket",inst2->S00_AXI_tlm_aximm_read_socket);
	pfm_dynamic_smartconn_data_0_0_sc*  inst3=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	registerTlmSocket("BLP_S_AXI_DATA_H2C_00_tlm_aximm_write_socket",inst3->S00_AXI_tlm_aximm_write_socket);
	pfm_dynamic_xbar_3_sc*  inst4=dynamic_cast<pfm_dynamic_xbar_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_3"));
	registerTlmSocket("BLP_S_AXI_CTRL_USER_00_tlm_aximm_read_socket",inst4->target_0_rd_socket);
	pfm_dynamic_xbar_3_sc*  inst5=dynamic_cast<pfm_dynamic_xbar_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_3"));
	registerTlmSocket("BLP_S_AXI_CTRL_USER_00_tlm_aximm_write_socket",inst5->target_0_wr_socket);
}

void pfm_dynamic_sci::before_end_of_elaboration() {
	
	pfm_dynamic_auto_cc_0_sc*  inst_0=dynamic_cast<pfm_dynamic_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_0"));
	pfm_dynamic_m02_regslice_4_sc*  inst_1=dynamic_cast<pfm_dynamic_m02_regslice_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m02_regslice_4"));
	xtlm_aximm_transaction_logger* log_inst_0 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_0");
	log_inst_0->setProxyRef(inst_0, inst_1, "pfm_dynamic_auto_cc_0_M_AXI_TLM", "pfm_dynamic_m02_regslice_4_S_AXI_TLM", log_inst_0->m_transactionLogger);
	
	if(inst_0==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_0_sc"<<std::endl;
	}
	if(inst_1==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m02_regslice_4_sc"<<std::endl;
	}
	
	if (inst_0!=NULL && inst_1!=NULL) {
		inst_0->M_INITIATOR_rd_socket->bind(*(log_inst_0->tar_rd_skt));
		log_inst_0->init_rd_skt->bind(*(inst_1->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_auto_cc_0_sc*  inst_4=dynamic_cast<pfm_dynamic_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_0"));
	pfm_dynamic_m02_regslice_4_sc*  inst_5=dynamic_cast<pfm_dynamic_m02_regslice_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m02_regslice_4"));
	
	if(inst_4==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_0_sc"<<std::endl;
	}
	if(inst_5==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m02_regslice_4_sc"<<std::endl;
	}
	
	if (inst_4!=NULL && inst_5!=NULL) {
		inst_4->M_INITIATOR_wr_socket->bind(*(log_inst_0->tar_wr_skt));
		log_inst_0->init_wr_skt->bind(*(inst_5->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_xbar_3_sc*  inst_8=dynamic_cast<pfm_dynamic_xbar_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_3"));
	pfm_dynamic_m01_regslice_4_sc*  inst_9=dynamic_cast<pfm_dynamic_m01_regslice_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_4"));
	xtlm_aximm_transaction_logger* log_inst_1 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_1");
	log_inst_1->setProxyRef(inst_8, inst_9, "pfm_dynamic_xbar_3_M01_AXI_TLM", "pfm_dynamic_m01_regslice_4_S_AXI_TLM", log_inst_1->m_transactionLogger);
	
	if(inst_8==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_3_sc"<<std::endl;
	}
	if(inst_9==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_4_sc"<<std::endl;
	}
	
	if (inst_8!=NULL && inst_9!=NULL) {
		inst_8->initiator_1_rd_socket->bind(*(log_inst_1->tar_rd_skt));
		log_inst_1->init_rd_skt->bind(*(inst_9->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_3_sc*  inst_12=dynamic_cast<pfm_dynamic_xbar_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_3"));
	pfm_dynamic_m01_regslice_4_sc*  inst_13=dynamic_cast<pfm_dynamic_m01_regslice_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_4"));
	
	if(inst_12==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_3_sc"<<std::endl;
	}
	if(inst_13==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_4_sc"<<std::endl;
	}
	
	if (inst_12!=NULL && inst_13!=NULL) {
		inst_12->initiator_1_wr_socket->bind(*(log_inst_1->tar_wr_skt));
		log_inst_1->init_wr_skt->bind(*(inst_13->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_xbar_3_sc*  inst_16=dynamic_cast<pfm_dynamic_xbar_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_3"));
	pfm_dynamic_auto_cc_0_sc*  inst_17=dynamic_cast<pfm_dynamic_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_0"));
	xtlm_aximm_transaction_logger* log_inst_2 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_2");
	log_inst_2->setProxyRef(inst_16, inst_17, "pfm_dynamic_xbar_3_M02_AXI_TLM", "pfm_dynamic_auto_cc_0_S_AXI_TLM", log_inst_2->m_transactionLogger);
	
	if(inst_16==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_3_sc"<<std::endl;
	}
	if(inst_17==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_0_sc"<<std::endl;
	}
	
	if (inst_16!=NULL && inst_17!=NULL) {
		inst_16->initiator_2_rd_socket->bind(*(log_inst_2->tar_rd_skt));
		log_inst_2->init_rd_skt->bind(*(inst_17->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_3_sc*  inst_20=dynamic_cast<pfm_dynamic_xbar_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_3"));
	pfm_dynamic_auto_cc_0_sc*  inst_21=dynamic_cast<pfm_dynamic_auto_cc_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_0"));
	
	if(inst_20==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_3_sc"<<std::endl;
	}
	if(inst_21==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_0_sc"<<std::endl;
	}
	
	if (inst_20!=NULL && inst_21!=NULL) {
		inst_20->initiator_2_wr_socket->bind(*(log_inst_2->tar_wr_skt));
		log_inst_2->init_wr_skt->bind(*(inst_21->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_auto_cc_1_sc*  inst_24=dynamic_cast<pfm_dynamic_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_1"));
	pfm_dynamic_m00_regslice_0_sc*  inst_25=dynamic_cast<pfm_dynamic_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m00_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_3 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_3");
	log_inst_3->setProxyRef(inst_24, inst_25, "pfm_dynamic_auto_cc_1_M_AXI_TLM", "pfm_dynamic_m00_regslice_0_S_AXI_TLM", log_inst_3->m_transactionLogger);
	
	if(inst_24==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_1_sc"<<std::endl;
	}
	if(inst_25==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_24!=NULL && inst_25!=NULL) {
		inst_24->M_INITIATOR_rd_socket->bind(*(log_inst_3->tar_rd_skt));
		log_inst_3->init_rd_skt->bind(*(inst_25->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_auto_cc_1_sc*  inst_28=dynamic_cast<pfm_dynamic_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_1"));
	pfm_dynamic_m00_regslice_0_sc*  inst_29=dynamic_cast<pfm_dynamic_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m00_regslice_0"));
	
	if(inst_28==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_1_sc"<<std::endl;
	}
	if(inst_29==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_28!=NULL && inst_29!=NULL) {
		inst_28->M_INITIATOR_wr_socket->bind(*(log_inst_3->tar_wr_skt));
		log_inst_3->init_wr_skt->bind(*(inst_29->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_auto_cc_2_sc*  inst_32=dynamic_cast<pfm_dynamic_auto_cc_2_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_2"));
	pfm_dynamic_m01_regslice_5_sc*  inst_33=dynamic_cast<pfm_dynamic_m01_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_5"));
	xtlm_aximm_transaction_logger* log_inst_4 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_4");
	log_inst_4->setProxyRef(inst_32, inst_33, "pfm_dynamic_auto_cc_2_M_AXI_TLM", "pfm_dynamic_m01_regslice_5_S_AXI_TLM", log_inst_4->m_transactionLogger);
	
	if(inst_32==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_2_sc"<<std::endl;
	}
	if(inst_33==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_5_sc"<<std::endl;
	}
	
	if (inst_32!=NULL && inst_33!=NULL) {
		inst_32->M_INITIATOR_rd_socket->bind(*(log_inst_4->tar_rd_skt));
		log_inst_4->init_rd_skt->bind(*(inst_33->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_auto_cc_2_sc*  inst_36=dynamic_cast<pfm_dynamic_auto_cc_2_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_2"));
	pfm_dynamic_m01_regslice_5_sc*  inst_37=dynamic_cast<pfm_dynamic_m01_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_5"));
	
	if(inst_36==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_2_sc"<<std::endl;
	}
	if(inst_37==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_5_sc"<<std::endl;
	}
	
	if (inst_36!=NULL && inst_37!=NULL) {
		inst_36->M_INITIATOR_wr_socket->bind(*(log_inst_4->tar_wr_skt));
		log_inst_4->init_wr_skt->bind(*(inst_37->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_auto_cc_3_sc*  inst_40=dynamic_cast<pfm_dynamic_auto_cc_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_3"));
	pfm_dynamic_m02_regslice_5_sc*  inst_41=dynamic_cast<pfm_dynamic_m02_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m02_regslice_5"));
	xtlm_aximm_transaction_logger* log_inst_5 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_5");
	log_inst_5->setProxyRef(inst_40, inst_41, "pfm_dynamic_auto_cc_3_M_AXI_TLM", "pfm_dynamic_m02_regslice_5_S_AXI_TLM", log_inst_5->m_transactionLogger);
	
	if(inst_40==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_3_sc"<<std::endl;
	}
	if(inst_41==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m02_regslice_5_sc"<<std::endl;
	}
	
	if (inst_40!=NULL && inst_41!=NULL) {
		inst_40->M_INITIATOR_rd_socket->bind(*(log_inst_5->tar_rd_skt));
		log_inst_5->init_rd_skt->bind(*(inst_41->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_auto_cc_3_sc*  inst_44=dynamic_cast<pfm_dynamic_auto_cc_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_3"));
	pfm_dynamic_m02_regslice_5_sc*  inst_45=dynamic_cast<pfm_dynamic_m02_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m02_regslice_5"));
	
	if(inst_44==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_3_sc"<<std::endl;
	}
	if(inst_45==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m02_regslice_5_sc"<<std::endl;
	}
	
	if (inst_44!=NULL && inst_45!=NULL) {
		inst_44->M_INITIATOR_wr_socket->bind(*(log_inst_5->tar_wr_skt));
		log_inst_5->init_wr_skt->bind(*(inst_45->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_auto_cc_4_sc*  inst_48=dynamic_cast<pfm_dynamic_auto_cc_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_4"));
	pfm_dynamic_m03_regslice_0_sc*  inst_49=dynamic_cast<pfm_dynamic_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m03_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_6 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_6");
	log_inst_6->setProxyRef(inst_48, inst_49, "pfm_dynamic_auto_cc_4_M_AXI_TLM", "pfm_dynamic_m03_regslice_0_S_AXI_TLM", log_inst_6->m_transactionLogger);
	
	if(inst_48==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_4_sc"<<std::endl;
	}
	if(inst_49==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m03_regslice_0_sc"<<std::endl;
	}
	
	if (inst_48!=NULL && inst_49!=NULL) {
		inst_48->M_INITIATOR_rd_socket->bind(*(log_inst_6->tar_rd_skt));
		log_inst_6->init_rd_skt->bind(*(inst_49->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_auto_cc_4_sc*  inst_52=dynamic_cast<pfm_dynamic_auto_cc_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_4"));
	pfm_dynamic_m03_regslice_0_sc*  inst_53=dynamic_cast<pfm_dynamic_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m03_regslice_0"));
	
	if(inst_52==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_4_sc"<<std::endl;
	}
	if(inst_53==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m03_regslice_0_sc"<<std::endl;
	}
	
	if (inst_52!=NULL && inst_53!=NULL) {
		inst_52->M_INITIATOR_wr_socket->bind(*(log_inst_6->tar_wr_skt));
		log_inst_6->init_wr_skt->bind(*(inst_53->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_auto_cc_5_sc*  inst_56=dynamic_cast<pfm_dynamic_auto_cc_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_5"));
	pfm_dynamic_m04_regslice_0_sc*  inst_57=dynamic_cast<pfm_dynamic_m04_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m04_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_7 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_7");
	log_inst_7->setProxyRef(inst_56, inst_57, "pfm_dynamic_auto_cc_5_M_AXI_TLM", "pfm_dynamic_m04_regslice_0_S_AXI_TLM", log_inst_7->m_transactionLogger);
	
	if(inst_56==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_5_sc"<<std::endl;
	}
	if(inst_57==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m04_regslice_0_sc"<<std::endl;
	}
	
	if (inst_56!=NULL && inst_57!=NULL) {
		inst_56->M_INITIATOR_rd_socket->bind(*(log_inst_7->tar_rd_skt));
		log_inst_7->init_rd_skt->bind(*(inst_57->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_auto_cc_5_sc*  inst_60=dynamic_cast<pfm_dynamic_auto_cc_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_5"));
	pfm_dynamic_m04_regslice_0_sc*  inst_61=dynamic_cast<pfm_dynamic_m04_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m04_regslice_0"));
	
	if(inst_60==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_5_sc"<<std::endl;
	}
	if(inst_61==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m04_regslice_0_sc"<<std::endl;
	}
	
	if (inst_60!=NULL && inst_61!=NULL) {
		inst_60->M_INITIATOR_wr_socket->bind(*(log_inst_7->tar_wr_skt));
		log_inst_7->init_wr_skt->bind(*(inst_61->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_s00_regslice_0_sc*  inst_64=dynamic_cast<pfm_dynamic_s00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_s00_regslice_0"));
	pfm_dynamic_xbar_4_sc*  inst_65=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	xtlm_aximm_transaction_logger* log_inst_8 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_8");
	log_inst_8->setProxyRef(inst_64, inst_65, "pfm_dynamic_s00_regslice_0_M_AXI_TLM", "pfm_dynamic_xbar_4_S00_AXI_TLM", log_inst_8->m_transactionLogger);
	
	if(inst_64==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_s00_regslice_0_sc"<<std::endl;
	}
	if(inst_65==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	
	if (inst_64!=NULL && inst_65!=NULL) {
		inst_64->M_INITIATOR_rd_socket->bind(*(log_inst_8->tar_rd_skt));
		log_inst_8->init_rd_skt->bind(*(inst_65->target_0_rd_socket));
	}
	
	pfm_dynamic_s00_regslice_0_sc*  inst_68=dynamic_cast<pfm_dynamic_s00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_s00_regslice_0"));
	pfm_dynamic_xbar_4_sc*  inst_69=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	
	if(inst_68==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_s00_regslice_0_sc"<<std::endl;
	}
	if(inst_69==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	
	if (inst_68!=NULL && inst_69!=NULL) {
		inst_68->M_INITIATOR_wr_socket->bind(*(log_inst_8->tar_wr_skt));
		log_inst_8->init_wr_skt->bind(*(inst_69->target_0_wr_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_72=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_1_sc*  inst_73=dynamic_cast<pfm_dynamic_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_1"));
	xtlm_aximm_transaction_logger* log_inst_9 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_9");
	log_inst_9->setProxyRef(inst_72, inst_73, "pfm_dynamic_xbar_4_M00_AXI_TLM", "pfm_dynamic_auto_cc_1_S_AXI_TLM", log_inst_9->m_transactionLogger);
	
	if(inst_72==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_73==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_1_sc"<<std::endl;
	}
	
	if (inst_72!=NULL && inst_73!=NULL) {
		inst_72->initiator_0_rd_socket->bind(*(log_inst_9->tar_rd_skt));
		log_inst_9->init_rd_skt->bind(*(inst_73->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_76=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_1_sc*  inst_77=dynamic_cast<pfm_dynamic_auto_cc_1_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_1"));
	
	if(inst_76==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_77==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_1_sc"<<std::endl;
	}
	
	if (inst_76!=NULL && inst_77!=NULL) {
		inst_76->initiator_0_wr_socket->bind(*(log_inst_9->tar_wr_skt));
		log_inst_9->init_wr_skt->bind(*(inst_77->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_80=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_2_sc*  inst_81=dynamic_cast<pfm_dynamic_auto_cc_2_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_2"));
	xtlm_aximm_transaction_logger* log_inst_10 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_10");
	log_inst_10->setProxyRef(inst_80, inst_81, "pfm_dynamic_xbar_4_M01_AXI_TLM", "pfm_dynamic_auto_cc_2_S_AXI_TLM", log_inst_10->m_transactionLogger);
	
	if(inst_80==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_81==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_2_sc"<<std::endl;
	}
	
	if (inst_80!=NULL && inst_81!=NULL) {
		inst_80->initiator_1_rd_socket->bind(*(log_inst_10->tar_rd_skt));
		log_inst_10->init_rd_skt->bind(*(inst_81->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_84=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_2_sc*  inst_85=dynamic_cast<pfm_dynamic_auto_cc_2_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_2"));
	
	if(inst_84==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_85==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_2_sc"<<std::endl;
	}
	
	if (inst_84!=NULL && inst_85!=NULL) {
		inst_84->initiator_1_wr_socket->bind(*(log_inst_10->tar_wr_skt));
		log_inst_10->init_wr_skt->bind(*(inst_85->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_88=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_3_sc*  inst_89=dynamic_cast<pfm_dynamic_auto_cc_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_3"));
	xtlm_aximm_transaction_logger* log_inst_11 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_11");
	log_inst_11->setProxyRef(inst_88, inst_89, "pfm_dynamic_xbar_4_M02_AXI_TLM", "pfm_dynamic_auto_cc_3_S_AXI_TLM", log_inst_11->m_transactionLogger);
	
	if(inst_88==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_89==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_3_sc"<<std::endl;
	}
	
	if (inst_88!=NULL && inst_89!=NULL) {
		inst_88->initiator_2_rd_socket->bind(*(log_inst_11->tar_rd_skt));
		log_inst_11->init_rd_skt->bind(*(inst_89->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_92=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_3_sc*  inst_93=dynamic_cast<pfm_dynamic_auto_cc_3_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_3"));
	
	if(inst_92==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_93==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_3_sc"<<std::endl;
	}
	
	if (inst_92!=NULL && inst_93!=NULL) {
		inst_92->initiator_2_wr_socket->bind(*(log_inst_11->tar_wr_skt));
		log_inst_11->init_wr_skt->bind(*(inst_93->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_96=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_4_sc*  inst_97=dynamic_cast<pfm_dynamic_auto_cc_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_4"));
	xtlm_aximm_transaction_logger* log_inst_12 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_12");
	log_inst_12->setProxyRef(inst_96, inst_97, "pfm_dynamic_xbar_4_M03_AXI_TLM", "pfm_dynamic_auto_cc_4_S_AXI_TLM", log_inst_12->m_transactionLogger);
	
	if(inst_96==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_97==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_4_sc"<<std::endl;
	}
	
	if (inst_96!=NULL && inst_97!=NULL) {
		inst_96->initiator_3_rd_socket->bind(*(log_inst_12->tar_rd_skt));
		log_inst_12->init_rd_skt->bind(*(inst_97->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_100=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_4_sc*  inst_101=dynamic_cast<pfm_dynamic_auto_cc_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_4"));
	
	if(inst_100==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_101==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_4_sc"<<std::endl;
	}
	
	if (inst_100!=NULL && inst_101!=NULL) {
		inst_100->initiator_3_wr_socket->bind(*(log_inst_12->tar_wr_skt));
		log_inst_12->init_wr_skt->bind(*(inst_101->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_104=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_5_sc*  inst_105=dynamic_cast<pfm_dynamic_auto_cc_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_5"));
	xtlm_aximm_transaction_logger* log_inst_13 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_13");
	log_inst_13->setProxyRef(inst_104, inst_105, "pfm_dynamic_xbar_4_M04_AXI_TLM", "pfm_dynamic_auto_cc_5_S_AXI_TLM", log_inst_13->m_transactionLogger);
	
	if(inst_104==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_105==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_5_sc"<<std::endl;
	}
	
	if (inst_104!=NULL && inst_105!=NULL) {
		inst_104->initiator_4_rd_socket->bind(*(log_inst_13->tar_rd_skt));
		log_inst_13->init_rd_skt->bind(*(inst_105->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_xbar_4_sc*  inst_108=dynamic_cast<pfm_dynamic_xbar_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xbar_4"));
	pfm_dynamic_auto_cc_5_sc*  inst_109=dynamic_cast<pfm_dynamic_auto_cc_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_auto_cc_5"));
	
	if(inst_108==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xbar_4_sc"<<std::endl;
	}
	if(inst_109==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_auto_cc_5_sc"<<std::endl;
	}
	
	if (inst_108!=NULL && inst_109!=NULL) {
		inst_108->initiator_4_wr_socket->bind(*(log_inst_13->tar_wr_skt));
		log_inst_13->init_wr_skt->bind(*(inst_109->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_m00_regslice_0_sc*  inst_112=dynamic_cast<pfm_dynamic_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m00_regslice_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_113=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_14 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_14");
	log_inst_14->setProxyRef(inst_112, inst_113, "pfm_dynamic_m00_regslice_0_M_AXI_TLM", "pfm_dynamic_dpa_hub_0_S_AXIFIFO_TLM", log_inst_14->m_transactionLogger);
	
	if(inst_112==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m00_regslice_0_sc"<<std::endl;
	}
	if(inst_113==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_112!=NULL && inst_113!=NULL) {
		inst_112->M_INITIATOR_rd_socket->bind(*(log_inst_14->tar_rd_skt));
		log_inst_14->init_rd_skt->bind(*(inst_113->axilite_rd_socket));
	}
	
	pfm_dynamic_m00_regslice_0_sc*  inst_116=dynamic_cast<pfm_dynamic_m00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m00_regslice_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_117=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	
	if(inst_116==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m00_regslice_0_sc"<<std::endl;
	}
	if(inst_117==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_116!=NULL && inst_117!=NULL) {
		inst_116->M_INITIATOR_wr_socket->bind(*(log_inst_14->tar_wr_skt));
		log_inst_14->init_wr_skt->bind(*(inst_117->axilite_wr_socket));
	}
	
	pfm_dynamic_m01_regslice_5_sc*  inst_120=dynamic_cast<pfm_dynamic_m01_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_5"));
	pfm_dynamic_dpa_hub_0_sc*  inst_121=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_15 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_15");
	log_inst_15->setProxyRef(inst_120, inst_121, "pfm_dynamic_m01_regslice_5_M_AXI_TLM", "pfm_dynamic_dpa_hub_0_S_AXIHUB_TLM", log_inst_15->m_transactionLogger);
	
	if(inst_120==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_5_sc"<<std::endl;
	}
	if(inst_121==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_120!=NULL && inst_121!=NULL) {
		inst_120->M_INITIATOR_rd_socket->bind(*(log_inst_15->tar_rd_skt));
		log_inst_15->init_rd_skt->bind(*(inst_121->s_axihub_rd_socket));
	}
	
	pfm_dynamic_m01_regslice_5_sc*  inst_124=dynamic_cast<pfm_dynamic_m01_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_5"));
	pfm_dynamic_dpa_hub_0_sc*  inst_125=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	
	if(inst_124==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_5_sc"<<std::endl;
	}
	if(inst_125==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_124!=NULL && inst_125!=NULL) {
		inst_124->M_INITIATOR_wr_socket->bind(*(log_inst_15->tar_wr_skt));
		log_inst_15->init_wr_skt->bind(*(inst_125->s_axihub_wr_socket));
	}
	
	pfm_dynamic_m02_regslice_5_sc*  inst_128=dynamic_cast<pfm_dynamic_m02_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m02_regslice_5"));
	pfm_dynamic_dpa_mon0_0_sc*  inst_129=dynamic_cast<pfm_dynamic_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon0_0"));
	xtlm_aximm_transaction_logger* log_inst_16 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_16");
	log_inst_16->setProxyRef(inst_128, inst_129, "pfm_dynamic_m02_regslice_5_M_AXI_TLM", "pfm_dynamic_dpa_mon0_0_S_AXI_TLM", log_inst_16->m_transactionLogger);
	
	if(inst_128==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m02_regslice_5_sc"<<std::endl;
	}
	if(inst_129==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon0_0_sc"<<std::endl;
	}
	
	if (inst_128!=NULL && inst_129!=NULL) {
		inst_128->M_INITIATOR_rd_socket->bind(*(log_inst_16->tar_rd_skt));
		log_inst_16->init_rd_skt->bind(*(inst_129->axilite_rd_skt));
	}
	
	pfm_dynamic_m02_regslice_5_sc*  inst_132=dynamic_cast<pfm_dynamic_m02_regslice_5_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m02_regslice_5"));
	pfm_dynamic_dpa_mon0_0_sc*  inst_133=dynamic_cast<pfm_dynamic_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon0_0"));
	
	if(inst_132==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m02_regslice_5_sc"<<std::endl;
	}
	if(inst_133==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon0_0_sc"<<std::endl;
	}
	
	if (inst_132!=NULL && inst_133!=NULL) {
		inst_132->M_INITIATOR_wr_socket->bind(*(log_inst_16->tar_wr_skt));
		log_inst_16->init_wr_skt->bind(*(inst_133->axilite_wr_skt));
	}
	
	pfm_dynamic_m03_regslice_0_sc*  inst_136=dynamic_cast<pfm_dynamic_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m03_regslice_0"));
	pfm_dynamic_dpa_mon1_0_sc*  inst_137=dynamic_cast<pfm_dynamic_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon1_0"));
	xtlm_aximm_transaction_logger* log_inst_17 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_17");
	log_inst_17->setProxyRef(inst_136, inst_137, "pfm_dynamic_m03_regslice_0_M_AXI_TLM", "pfm_dynamic_dpa_mon1_0_S_AXI_TLM", log_inst_17->m_transactionLogger);
	
	if(inst_136==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m03_regslice_0_sc"<<std::endl;
	}
	if(inst_137==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon1_0_sc"<<std::endl;
	}
	
	if (inst_136!=NULL && inst_137!=NULL) {
		inst_136->M_INITIATOR_rd_socket->bind(*(log_inst_17->tar_rd_skt));
		log_inst_17->init_rd_skt->bind(*(inst_137->axilite_rd_socket));
	}
	
	pfm_dynamic_m03_regslice_0_sc*  inst_140=dynamic_cast<pfm_dynamic_m03_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m03_regslice_0"));
	pfm_dynamic_dpa_mon1_0_sc*  inst_141=dynamic_cast<pfm_dynamic_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon1_0"));
	
	if(inst_140==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m03_regslice_0_sc"<<std::endl;
	}
	if(inst_141==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon1_0_sc"<<std::endl;
	}
	
	if (inst_140!=NULL && inst_141!=NULL) {
		inst_140->M_INITIATOR_wr_socket->bind(*(log_inst_17->tar_wr_skt));
		log_inst_17->init_wr_skt->bind(*(inst_141->axilite_wr_socket));
	}
	
	pfm_dynamic_m04_regslice_0_sc*  inst_144=dynamic_cast<pfm_dynamic_m04_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m04_regslice_0"));
	pfm_dynamic_dpa_mon2_0_sc*  inst_145=dynamic_cast<pfm_dynamic_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon2_0"));
	xtlm_aximm_transaction_logger* log_inst_18 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_18");
	log_inst_18->setProxyRef(inst_144, inst_145, "pfm_dynamic_m04_regslice_0_M_AXI_TLM", "pfm_dynamic_dpa_mon2_0_S_AXI_TLM", log_inst_18->m_transactionLogger);
	
	if(inst_144==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m04_regslice_0_sc"<<std::endl;
	}
	if(inst_145==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon2_0_sc"<<std::endl;
	}
	
	if (inst_144!=NULL && inst_145!=NULL) {
		inst_144->M_INITIATOR_rd_socket->bind(*(log_inst_18->tar_rd_skt));
		log_inst_18->init_rd_skt->bind(*(inst_145->axilite_rd_socket));
	}
	
	pfm_dynamic_m04_regslice_0_sc*  inst_148=dynamic_cast<pfm_dynamic_m04_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m04_regslice_0"));
	pfm_dynamic_dpa_mon2_0_sc*  inst_149=dynamic_cast<pfm_dynamic_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon2_0"));
	
	if(inst_148==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m04_regslice_0_sc"<<std::endl;
	}
	if(inst_149==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon2_0_sc"<<std::endl;
	}
	
	if (inst_148!=NULL && inst_149!=NULL) {
		inst_148->M_INITIATOR_wr_socket->bind(*(log_inst_18->tar_wr_skt));
		log_inst_18->init_wr_skt->bind(*(inst_149->axilite_wr_socket));
	}
	
	pfm_dynamic_dpa_mon0_0_sc*  inst_152=dynamic_cast<pfm_dynamic_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon0_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_153=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_19 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_19");
	log_inst_19->setProxyRef(inst_152, inst_153, "pfm_dynamic_dpa_mon0_0_TRACE_OUT_TLM", "pfm_dynamic_dpa_hub_0_TRACE_IN_0_TLM", log_inst_19->m_transactionLogger);
	
	if(inst_152==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon0_0_sc"<<std::endl;
	}
	if(inst_153==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_152!=NULL && inst_153!=NULL) {
		inst_152->trace_skt->bind(*(log_inst_19->tar_skt));
		log_inst_19->init_skt->bind(*(inst_153->trace_socket0));
	}
	
	pfm_dynamic_dpa_mon1_0_sc*  inst_156=dynamic_cast<pfm_dynamic_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon1_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_157=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_20 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_20");
	log_inst_20->setProxyRef(inst_156, inst_157, "pfm_dynamic_dpa_mon1_0_TRACE_OUT_0_TLM", "pfm_dynamic_dpa_hub_0_TRACE_IN_1_TLM", log_inst_20->m_transactionLogger);
	
	if(inst_156==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon1_0_sc"<<std::endl;
	}
	if(inst_157==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_156!=NULL && inst_157!=NULL) {
		inst_156->wr_trace_socket->bind(*(log_inst_20->tar_skt));
		log_inst_20->init_skt->bind(*(inst_157->trace_socket1));
	}
	
	pfm_dynamic_dpa_mon1_0_sc*  inst_160=dynamic_cast<pfm_dynamic_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon1_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_161=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_21 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_21");
	log_inst_21->setProxyRef(inst_160, inst_161, "pfm_dynamic_dpa_mon1_0_TRACE_OUT_1_TLM", "pfm_dynamic_dpa_hub_0_TRACE_IN_2_TLM", log_inst_21->m_transactionLogger);
	
	if(inst_160==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon1_0_sc"<<std::endl;
	}
	if(inst_161==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_160!=NULL && inst_161!=NULL) {
		inst_160->rd_trace_socket->bind(*(log_inst_21->tar_skt));
		log_inst_21->init_skt->bind(*(inst_161->trace_socket2));
	}
	
	pfm_dynamic_dpa_mon2_0_sc*  inst_164=dynamic_cast<pfm_dynamic_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon2_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_165=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_22 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_22");
	log_inst_22->setProxyRef(inst_164, inst_165, "pfm_dynamic_dpa_mon2_0_TRACE_OUT_0_TLM", "pfm_dynamic_dpa_hub_0_TRACE_IN_3_TLM", log_inst_22->m_transactionLogger);
	
	if(inst_164==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon2_0_sc"<<std::endl;
	}
	if(inst_165==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_164!=NULL && inst_165!=NULL) {
		inst_164->wr_trace_socket->bind(*(log_inst_22->tar_skt));
		log_inst_22->init_skt->bind(*(inst_165->trace_socket3));
	}
	
	pfm_dynamic_dpa_mon2_0_sc*  inst_168=dynamic_cast<pfm_dynamic_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon2_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_169=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_23 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_23");
	log_inst_23->setProxyRef(inst_168, inst_169, "pfm_dynamic_dpa_mon2_0_TRACE_OUT_1_TLM", "pfm_dynamic_dpa_hub_0_TRACE_IN_4_TLM", log_inst_23->m_transactionLogger);
	
	if(inst_168==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon2_0_sc"<<std::endl;
	}
	if(inst_169==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_168!=NULL && inst_169!=NULL) {
		inst_168->rd_trace_socket->bind(*(log_inst_23->tar_skt));
		log_inst_23->init_skt->bind(*(inst_169->trace_socket4));
	}
	
	pfm_dynamic_profile_vip_0_0_sc*  inst_172=dynamic_cast<pfm_dynamic_profile_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_profile_vip_0_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_173=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_24 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_24");
	log_inst_24->setProxyRef(inst_172, inst_173, "pfm_dynamic_profile_vip_0_0_M_AXI_TLM", "pfm_dynamic_dpa_hub_0_S_AXIMM_TLM", log_inst_24->m_transactionLogger);
	
	if(inst_172==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_profile_vip_0_0_sc"<<std::endl;
	}
	if(inst_173==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_172!=NULL && inst_173!=NULL) {
		inst_172->M_INITIATOR_rd_socket->bind(*(log_inst_24->tar_rd_skt));
		log_inst_24->init_rd_skt->bind(*(inst_173->s_aximm_rd_socket));
	}
	
	pfm_dynamic_profile_vip_0_0_sc*  inst_176=dynamic_cast<pfm_dynamic_profile_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_profile_vip_0_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_177=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	
	if(inst_176==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_profile_vip_0_0_sc"<<std::endl;
	}
	if(inst_177==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_176!=NULL && inst_177!=NULL) {
		inst_176->M_INITIATOR_wr_socket->bind(*(log_inst_24->tar_wr_skt));
		log_inst_24->init_wr_skt->bind(*(inst_177->s_aximm_wr_socket));
	}
	
	pfm_dynamic_smartconn_data_0_0_sc*  inst_180=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	xsc_sim_conn_base*  inst_181=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_d216_sci"));
	
	if(inst_180==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_dynamic_smartconn_data_0_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_181==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_180!=NULL && inst_181!=NULL && inst_181->getTlmSocketByName("S00_AXI_tlm_aximm_read_socket")!=NULL) {
		inst_180->M00_AXI_tlm_aximm_read_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_181->getTlmSocketByName("S00_AXI_tlm_aximm_read_socket")));
	}
	
	pfm_dynamic_smartconn_data_0_0_sc*  inst_184=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	xsc_sim_conn_base*  inst_185=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_d216_sci"));
	
	if(inst_184==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_dynamic_smartconn_data_0_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_185==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_184!=NULL && inst_185!=NULL && inst_185->getTlmSocketByName("S00_AXI_tlm_aximm_write_socket")!=NULL) {
		inst_184->M00_AXI_tlm_aximm_write_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_185->getTlmSocketByName("S00_AXI_tlm_aximm_write_socket")));
	}
	
	pfm_dynamic_smartconn_data_0_0_sc*  inst_188=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	xsc_sim_conn_base*  inst_189=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_sci"));
	
	if(inst_188==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_dynamic_smartconn_data_0_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_189==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_188!=NULL && inst_189!=NULL && inst_189->getTlmSocketByName("S00_AXI_tlm_aximm_read_socket")!=NULL) {
		inst_188->M01_AXI_tlm_aximm_read_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_189->getTlmSocketByName("S00_AXI_tlm_aximm_read_socket")));
	}
	
	pfm_dynamic_smartconn_data_0_0_sc*  inst_192=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	xsc_sim_conn_base*  inst_193=dynamic_cast<xsc_sim_conn_base*>(xsc::utils::xsc_sim_manager::getInstancePtr("bd_5dca_sci"));
	
	if(inst_192==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind pfm_dynamic_smartconn_data_0_0_sc, Skipping this connection"<<std::endl;
	}
	if(inst_193==NULL) {
		std::cout<<"WARNING: While binding sockets cannot find socket object instance to bind xsc_sim_conn_base, Skipping this connection"<<std::endl;
	}
	
	if (inst_192!=NULL && inst_193!=NULL && inst_193->getTlmSocketByName("S00_AXI_tlm_aximm_write_socket")!=NULL) {
		inst_192->M01_AXI_tlm_aximm_write_socket->bind(*static_cast<xtlm::xtlm_aximm_target_socket*>(inst_193->getTlmSocketByName("S00_AXI_tlm_aximm_write_socket")));
	}
	
	pfm_dynamic_smartconn_data_0_0_sc*  inst_196=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	pfm_dynamic_profile_vip_0_0_sc*  inst_197=dynamic_cast<pfm_dynamic_profile_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_profile_vip_0_0"));
	xtlm_aximm_transaction_logger* log_inst_27 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_27");
	log_inst_27->setProxyRef(inst_196, inst_197, "pfm_dynamic_smartconn_data_0_0_M02_AXI_tlm", "pfm_dynamic_profile_vip_0_0_S_AXI_TLM", log_inst_27->m_transactionLogger);
	
	if(inst_196==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_smartconn_data_0_0_sc"<<std::endl;
	}
	if(inst_197==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_profile_vip_0_0_sc"<<std::endl;
	}
	
	if (inst_196!=NULL && inst_197!=NULL) {
		inst_196->M02_AXI_tlm_aximm_read_socket->bind(*(log_inst_27->tar_rd_skt));
		log_inst_27->init_rd_skt->bind(*(inst_197->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_smartconn_data_0_0_sc*  inst_200=dynamic_cast<pfm_dynamic_smartconn_data_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_smartconn_data_0_0"));
	pfm_dynamic_profile_vip_0_0_sc*  inst_201=dynamic_cast<pfm_dynamic_profile_vip_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_profile_vip_0_0"));
	
	if(inst_200==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_smartconn_data_0_0_sc"<<std::endl;
	}
	if(inst_201==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_profile_vip_0_0_sc"<<std::endl;
	}
	
	if (inst_200!=NULL && inst_201!=NULL) {
		inst_200->M02_AXI_tlm_aximm_write_socket->bind(*(log_inst_27->tar_wr_skt));
		log_inst_27->init_wr_skt->bind(*(inst_201->S_TARGET_wr_socket));
	}
	
	pfm_dynamic_m01_regslice_4_sc*  inst_204=dynamic_cast<pfm_dynamic_m01_regslice_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_4"));
	pfm_dynamic_s00_regslice_0_sc*  inst_205=dynamic_cast<pfm_dynamic_s00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_s00_regslice_0"));
	xtlm_aximm_transaction_logger* log_inst_28 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_28");
	log_inst_28->setProxyRef(inst_204, inst_205, "pfm_dynamic_m01_regslice_4_M_AXI_TLM", "pfm_dynamic_s00_regslice_0_S_AXI_TLM", log_inst_28->m_transactionLogger);
	
	if(inst_204==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_4_sc"<<std::endl;
	}
	if(inst_205==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_s00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_204!=NULL && inst_205!=NULL) {
		inst_204->M_INITIATOR_rd_socket->bind(*(log_inst_28->tar_rd_skt));
		log_inst_28->init_rd_skt->bind(*(inst_205->S_TARGET_rd_socket));
	}
	
	pfm_dynamic_m01_regslice_4_sc*  inst_208=dynamic_cast<pfm_dynamic_m01_regslice_4_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_m01_regslice_4"));
	pfm_dynamic_s00_regslice_0_sc*  inst_209=dynamic_cast<pfm_dynamic_s00_regslice_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_s00_regslice_0"));
	
	if(inst_208==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_m01_regslice_4_sc"<<std::endl;
	}
	if(inst_209==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_s00_regslice_0_sc"<<std::endl;
	}
	
	if (inst_208!=NULL && inst_209!=NULL) {
		inst_208->M_INITIATOR_wr_socket->bind(*(log_inst_28->tar_wr_skt));
		log_inst_28->init_wr_skt->bind(*(inst_209->S_TARGET_wr_socket));
	}
	
}
#ifdef MTI_SYSTEMC
SC_MODULE_EXPORT(pfm_dynamic_sci);
#endif

#ifdef XM_SYSTEMC
XMSC_MODULE_EXPORT(pfm_dynamic_sci);
#endif

#ifdef RIVIERA
SC_MODULE_EXPORT(pfm_dynamic_sci);
#endif

